services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5003:5003"
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "8082:8082"